
name: 'coffee_shop_hilton_revenue'
version: '1.0.0'
config-version: 2

profile: 'coffee_shop_hilton_revenue'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:     
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  coffee_shop_hilton_revenue:
    - name: coffee_orders
    - name: weekly_revenue_customer_type
    - name: weekley_revenue_product_category
    - name: product_category_jinga_practice
